### ISSUE TITLE
Question: Juice2

### ISSUE THREAD

**Issue by lb-** [SachaG/meteor-juice#6]
Hi Sacha,

Any plans to move to Juice2
https://www.npmjs.com/package/juice2

Any reasons why not?

**Comment by SachaG** [comment]
Sure, I didn't even know there was a juice2 package. PRs welcome :)

**Comment by lb-** [comment]
@SachaG upon closer inspection, it appears that the original juice package has been more recently updated (ironic) and has a slightly different api, might be best to keep as is. Thanks though

https://github.com/andrewrk/juice
